CC=gcc
CFLAGS=-g -std=c99 -Wall
LDFLAGS=-lm

test3:
	./part3 
	./part3 "only one parameter"
	./part3 "biggest parameter" "at" "start"
	./part3 "biggest" "parameter" "at" "end" "very very very big parameter"
	./part3 "answer" "somewhere" "in" "the" "middle"
	./part3 "two" "strings" "the" "same" "length" "ha ha !"

test4:
	./part4 
	./part4 -f
	./part4 -300
	./part4 -f -3
	./part4 -c
	./part4 -c -300
	./part4 -c 10
	./part4 -f 20

test5:
	./part5 
	./part5 index
	./part5 s.
	./part5 x.i
	./part5 c.in
	./part5 input.txt
	./part5 input1.txt
	./part5 input2.txt
	